### ISSUE TITLE
When to evaluate errors in some properties

### ISSUE THREAD

**Issue by jenguidanos** [EVerest/libcbv2g#19]
Hello, and first of all, thanks for the work you did with this library, especially with the generator.

I am reviewing the deserialization of the ScheduleExchangeReq message and noticed something I would like to understand better. In the [decode_iso20_Dynamic_SEReqControlModeType][1] property, the first grammarId, 328, does not have a second error validation as the following grammarId have, for example in grammarId 329 you can see this second validation under the comment `// if nothing went wrong, the error of exi_basetypes_decoder_nbit_uint is evaluated here`

Does anyone know why in grammarId 328, departureTime, this second validation is not performed?

[1]:https://github.com/EVerest/libcbv2g/blob/0966194e995cdb741b02547ddd9abd67455691d9/lib/cbv2g/iso_20/iso20_CommonMessages_Decoder.c#L15079

**Comment by barsnick** [comment]
> Does anyone know why in grammarId 328, departureTime, this second validation is not performed?

What you are looking for is wrapped in `decode_exi_type_uint32()` for the `DepartureTime` value.

`MinimumSOC` is of type `byte`, whose decoder does not have such a wrapper.

(That does remind me, it may be a good idea to introduce such a wrapper, to reduce code duplication.)

**Comment by jenguidanos** [comment]
Thanks barsnick, it makes sense what you say.

In my case I have used the OpenV2G library on a microcontroller with limited resources and reducing the base size of the generated code has been an important task.

Thanks for the answer.
